### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by ftgreat** [nyonicai/nyonic-public#3]
Thanks for your tech report and sharing details.
In the report, Basic Capabilities & Multilingual Understanding are selected for Experiment Results.

Why are other metrics not considered in the paper, such as MMLU, MATH?

Thanks.

**Comment by eastdogzhou** [comment]
Thanks for asking.

We are continuously optimizing the model and will also consider expanding the evaluation metrics in the future.

**Comment by ftgreat** [comment]
Thank you for your response. 

Currently, open-source models show greatly improved performance on tasks like MMLU, MATH, and complex reasoning tasks. 
If we use the existing data set ratios, can we achieve similar results? Will any other datasets should be introduced? 
I would appreciate your thoughts and suggestions. Thank you.

**Comment by eastdogzhou** [comment]
We didn't see a significant change of general benchmark among our several datamix; since we focus more on language mix.

In order to achieve better results of MMLU or MATH, I would suggest to mix more data relevant to these topics. One thing to notice is that one may need to spend some effort on data decontamination.

**Comment by ftgreat** [comment]
Could you please list some papers about data decontamination？

Thank a lot.
